import React from 'react';
import { SiteLayout } from './SiteLayout';
import { CONTACT_EMAIL } from '../config/site';

export type LegalDoc = 'terms' | 'privacy';

const UPDATED = '5 October 2026';

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <section className="space-y-3">
    <h2 className="font-serif text-xl text-[#F5F1E8]">{title}</h2>
    <div className="space-y-3 text-[15px] leading-7 text-[#B9B4A8]">{children}</div>
  </section>
);

const Privacy = () => (
  <>
    <Section title="What this app collects">
      <p>
        FridgeChef has no accounts and no advertising cookies. We only handle what you choose to give it: photos you
        upload or take (fridge, receipt or plate), ingredient lists you type, voice input when you turn the microphone
        on, and messages you send through the contact form.
      </p>
    </Section>
    <Section title="Where your photos and text go">
      <p>
        To identify ingredients and write recipes, photos and text are sent from your browser to our server, which
        forwards them to Google's Gemini API. Our server does not save them. Google processes them under its own{' '}
        <a className="underline decoration-[#FF5A3C] underline-offset-4 hover:text-[#F5F1E8]" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">
          privacy policy
        </a>
        .
      </p>
      <p>
        If Gemini is unavailable, text requests (never photos or audio) are sent to Groq instead, which processes them
        under its own{' '}
        <a className="underline decoration-[#FF5A3C] underline-offset-4 hover:text-[#F5F1E8]" href="https://groq.com/privacy-policy/" target="_blank" rel="noreferrer">
          privacy policy
        </a>
        .
      </p>
      <p>Photos are resized in your browser before upload, so we never receive the original file.</p>
    </Section>
    <Section title="Camera and microphone">
      <p>
        The camera is used only while the scanner or plating guide is open, and it switches off when you close it.
        Voice features use your browser's built-in speech recognition. In Chrome, that audio is processed by Google.
      </p>
    </Section>
    <Section title="What stays on your device">
      <p>
        Saved recipes, your shopping list and your cookie-banner choice are kept in your browser's local storage. A
        session flag remembers that you have seen the intro. Clearing your browser data removes all of it.
      </p>
    </Section>
    <Section title="Analytics">
      <p>
        If you accept analytics in the cookie banner, the app sends anonymous usage events (which page or tab you opened,
        and the referring site) to our own server. We do not store your IP address, use third-party analytics, or set
        cookies for this. Choose "Decline" or change your choice any time under Cookie settings in the footer.
      </p>
    </Section>
    <Section title="Contact form">
      <p>
        Messages you send through the contact form, including your name and email, are stored on our server so we can
        reply. Ask us to delete them at any time.
      </p>
    </Section>
    <Section title="Contact">
      <p>
        Questions about this policy: use the <a className="underline underline-offset-4 hover:text-[#F5F1E8]" href="#/contact">contact page</a>
        {CONTACT_EMAIL ? (
          <>
            {' '}or email <a className="underline underline-offset-4 hover:text-[#F5F1E8]" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          </>
        ) : null}
        .
      </p>
    </Section>
    <Section title="Third parties">
      <p>Fonts load from Google Fonts, which receives your IP address when the page loads. There are no other trackers.</p>
    </Section>
  </>
);

const Terms = () => (
  <>
    <Section title="Using FridgeChef">
      <p>
        FridgeChef is a free cooking aid. You can use it for personal, non-commercial cooking. Please do not try to
        overload the service or use it to process images that are not yours to share.
      </p>
    </Section>
    <Section title="AI suggestions can be wrong">
      <p>
        Ingredient detection, freshness estimates, nutrition numbers, prices and recipes are generated by AI and may be
        inaccurate. They are suggestions, not advice.
      </p>
      <p>
        Always check allergens yourself, cook meat, fish and eggs to safe temperatures, and throw out food that looks or
        smells off, whatever the app says. FridgeChef is not a substitute for medical or dietary advice.
      </p>
    </Section>
    <Section title="Sample data">
      <p>
        Household members, sensor readings, prices and leaderboards shown in the app are demonstration data unless you
        entered them yourself.
      </p>
    </Section>
    <Section title="No warranty">
      <p>
        The service is provided as is, without any warranty. To the extent the law allows, we are not liable for losses
        arising from use of the app or its suggestions.
      </p>
    </Section>
    <Section title="Changes">
      <p>We may update these terms. The date at the top shows when they last changed.</p>
    </Section>
  </>
);

// Terms of Service and Privacy Policy, reached via #/terms and #/privacy
export const LegalPage: React.FC<{ doc: LegalDoc }> = ({ doc }) => {
  const isTerms = doc === 'terms';
  return (
    <SiteLayout
      title={isTerms ? 'Terms of Service' : 'Privacy Policy'}
      description={
        isTerms
          ? 'The terms for using FridgeChef, including limits of AI cooking suggestions.'
          : 'What FridgeChef collects, where photos are sent, and what stays on your device.'
      }
    >
      <h1 className="font-serif text-4xl sm:text-5xl">{isTerms ? 'Terms of Service' : 'Privacy Policy'}</h1>
      <p className="mt-3 text-sm text-[#8F8A80]">Last updated {UPDATED}</p>
      <div className="mt-10 space-y-10 border-t border-[#F5F1E8]/10 pt-10">{isTerms ? <Terms /> : <Privacy />}</div>
    </SiteLayout>
  );
};
